/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TelasDoPrograma;

import Classes.Adm;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Pablo
 */
public class TelaOpcoesAdm extends javax.swing.JInternalFrame {

    private StringBuilder sb = new StringBuilder();

    /**
     * Creates new form TelaOpcoesAdm
     */
    public TelaOpcoesAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastroDeFuncionarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recebeNomeMembro = new javax.swing.JTextField();
        recebeRuaMembro = new javax.swing.JTextField();
        recebeEmailMembro = new javax.swing.JTextField();
        recebeNumeroMembro = new javax.swing.JTextField();
        recebeBairroMembro = new javax.swing.JTextField();
        recebeCidadeMembro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTNconfirmaCadastroMembro = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        recebeLoginMembro = new javax.swing.JTextField();
        recebeSenhaMembro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        opcSelect = new javax.swing.JList<>();
        recebeCpfMembro = new javax.swing.JFormattedTextField();
        recebeTelMembro = new javax.swing.JFormattedTextField();
        recebeCepMembro = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        recebeCodigoDosMembros = new javax.swing.JTextField();
        BotaoPesquisarMembros = new javax.swing.JButton();
        BotaoDeletarMembros = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TelaMostrarMembros = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ReceberCodigoParaEditar = new javax.swing.JTextField();
        BotaoEditarCodigo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RecebeTel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        RecebeEmail = new javax.swing.JTextField();
        RecebeRua = new javax.swing.JTextField();
        RecebeBairro = new javax.swing.JTextField();
        RecebeNumero = new javax.swing.JTextField();
        RecebeCep = new javax.swing.JTextField();
        RecebeLogin = new javax.swing.JTextField();
        RecebeSenha = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        RecebeCidade = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarTodosOsMembros = new javax.swing.JTextPane();
        VerTodosOsMembros = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Opções De Adiministrador");

        painelCadastroDeFuncionarios.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setText("Cadastrar Membro");

        recebeRuaMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeRuaMembroActionPerformed(evt);
            }
        });

        recebeNumeroMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeNumeroMembroActionPerformed(evt);
            }
        });

        recebeBairroMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeBairroMembroActionPerformed(evt);
            }
        });

        recebeCidadeMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeCidadeMembroActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Tel");

        jLabel5.setText("E-mail");

        jLabel6.setText("Rua");

        jLabel7.setText("Numero");

        jLabel8.setText("Bairro");

        jLabel9.setText("Cidade");

        jLabel10.setText("CEP");

        BTNconfirmaCadastroMembro.setText("Cadastrar");
        BTNconfirmaCadastroMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNconfirmaCadastroMembroActionPerformed(evt);
            }
        });

        jLabel21.setText("Login");

        jLabel22.setText("Senha");

        opcSelect.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "admin", "funcionario" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(opcSelect);

        try {
            recebeCpfMembro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            recebeTelMembro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            recebeCepMembro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout painelCadastroDeFuncionariosLayout = new javax.swing.GroupLayout(painelCadastroDeFuncionarios);
        painelCadastroDeFuncionarios.setLayout(painelCadastroDeFuncionariosLayout);
        painelCadastroDeFuncionariosLayout.setHorizontalGroup(
            painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                        .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(recebeRuaMembro, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(recebeNomeMembro)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(recebeTelMembro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recebeCpfMembro)
                            .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(recebeEmailMembro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(recebeNumeroMembro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                        .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recebeBairroMembro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(recebeCepMembro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21)
                                .addComponent(recebeCidadeMembro)
                                .addComponent(recebeLoginMembro, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                        .addComponent(BTNconfirmaCadastroMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebeSenhaMembro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelCadastroDeFuncionariosLayout.setVerticalGroup(
            painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(painelCadastroDeFuncionariosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeNomeMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeCpfMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeEmailMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeTelMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeRuaMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeNumeroMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeBairroMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeCidadeMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel21))
                .addGap(11, 11, 11)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeLoginMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recebeCepMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(2, 2, 2)
                .addGroup(painelCadastroDeFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recebeSenhaMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNconfirmaCadastroMembro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setText("Pesquisar Codigo");

        recebeCodigoDosMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeCodigoDosMembrosActionPerformed(evt);
            }
        });

        BotaoPesquisarMembros.setText("Pesquisar");
        BotaoPesquisarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarMembrosActionPerformed(evt);
            }
        });

        BotaoDeletarMembros.setText("Deletar");
        BotaoDeletarMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeletarMembrosActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(TelaMostrarMembros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(35, 35, 35)
                                .addComponent(recebeCodigoDosMembros))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotaoDeletarMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(BotaoPesquisarMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(recebeCodigoDosMembros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoPesquisarMembros)
                    .addComponent(BotaoDeletarMembros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel11.setText("Editar Membro");

        ReceberCodigoParaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberCodigoParaEditarActionPerformed(evt);
            }
        });

        BotaoEditarCodigo.setText("Atualizar");
        BotaoEditarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarCodigoActionPerformed(evt);
            }
        });

        jLabel13.setText("Codigo");

        jLabel14.setText("E-mail:");

        RecebeTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeTelActionPerformed(evt);
            }
        });

        jLabel15.setText("Tel:");

        jLabel16.setText("Rua:");

        jLabel17.setText("Bairro:");

        jLabel18.setText("Numero:");

        jLabel19.setText("CEP:");

        jLabel20.setText("Login:");

        jLabel23.setText("Senha:");

        RecebeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeEmailActionPerformed(evt);
            }
        });

        RecebeCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeCepActionPerformed(evt);
            }
        });

        RecebeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeLoginActionPerformed(evt);
            }
        });

        RecebeSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeSenhaActionPerformed(evt);
            }
        });

        jLabel24.setText("Cidade:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotaoEditarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReceberCodigoParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RecebeTel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RecebeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecebeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RecebeRua, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RecebeBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RecebeLogin)
                    .addComponent(RecebeCep)
                    .addComponent(RecebeSenha)
                    .addComponent(RecebeCidade))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReceberCodigoParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoEditarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(RecebeTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(RecebeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(RecebeCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RecebeCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(RecebeRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(RecebeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RecebeBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel23)
                            .addComponent(RecebeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(RecebeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel25.setText("Ver Todos os Membros");

        jScrollPane1.setViewportView(mostrarTodosOsMembros);

        VerTodosOsMembros.setText("Ver Todos");
        VerTodosOsMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerTodosOsMembrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(65, 65, 65))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerTodosOsMembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VerTodosOsMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelCadastroDeFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelCadastroDeFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        setBounds(300, 20, 899, 601);
    }// </editor-fold>//GEN-END:initComponents

    private void recebeNumeroMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeNumeroMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeNumeroMembroActionPerformed

    private void recebeBairroMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeBairroMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeBairroMembroActionPerformed

    private void recebeCidadeMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeCidadeMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeCidadeMembroActionPerformed

    private void recebeRuaMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeRuaMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeRuaMembroActionPerformed

    private void recebeCodigoDosMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeCodigoDosMembrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeCodigoDosMembrosActionPerformed

    private void RecebeTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeTelActionPerformed

    private void RecebeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeLoginActionPerformed

    private void RecebeSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeSenhaActionPerformed

    private void BTNconfirmaCadastroMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNconfirmaCadastroMembroActionPerformed
        String nOme = recebeNomeMembro.getText();
        String cPf = recebeCpfMembro.getText();
        String tEl = recebeTelMembro.getText();
        String eMail = recebeEmailMembro.getText();
        String rUa = recebeRuaMembro.getText();
        String nUmero = recebeNumeroMembro.getText();
        String bAirro = recebeBairroMembro.getText();
        String cIdade = recebeCidadeMembro.getText();
        String cEp = recebeCepMembro.getText();
        String log = recebeLoginMembro.getText();
        String senh = recebeSenhaMembro.getText();
        String opc1 = opcSelect.getSelectedValue();

        if (opc1 == "funcionario") {
            Adm fun = new Adm();
            fun.cadastrarF(nOme, cPf, tEl, eMail, rUa, bAirro, nUmero, cEp, cIdade, log, senh);
            JOptionPane.showMessageDialog(null, "Cadastro Funcionario " + nOme + " Feito com Sucesso!");
        }
        if (opc1 == "admin") {
            Adm adm = new Adm();
            adm.cadastrarA(WIDTH, nOme, cPf, tEl, eMail, rUa, bAirro, nUmero, cEp, cIdade, log, senh);
            JOptionPane.showMessageDialog(null, "Cadastro Administrador " + nOme + " Feito com Sucesso!");

        }
 // Limpar os campos de texto
    recebeNomeMembro.setText("");
    recebeCpfMembro.setText("");
    recebeTelMembro.setText("");
    recebeEmailMembro.setText("");
    recebeRuaMembro.setText("");
    recebeNumeroMembro.setText("");
    recebeBairroMembro.setText("");
    recebeCidadeMembro.setText("");
    recebeCepMembro.setText("");
    recebeLoginMembro.setText("");
    recebeSenhaMembro.setText("");
    }//GEN-LAST:event_BTNconfirmaCadastroMembroActionPerformed

    private void BotaoPesquisarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarMembrosActionPerformed
        // TODO add your handling code here:
        String codigoCliente = recebeCodigoDosMembros.getText();
        int codigo = Integer.parseInt(codigoCliente);

        StringBuilder sb = new StringBuilder();
        Classes.Adm.verMembroTela(codigo, sb);
        TelaMostrarMembros.setText(sb.toString());
    }//GEN-LAST:event_BotaoPesquisarMembrosActionPerformed

    private void BotaoDeletarMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeletarMembrosActionPerformed
        // TODO add your handling code here:
        String codigoCliente = recebeCodigoDosMembros.getText();
        int codigo = Integer.parseInt(codigoCliente);

        Classes.Adm.excluirMembroTela(codigo);
        JOptionPane.showMessageDialog(null, "Membro " + codigo + " Excluido com Sucesso!");

    }//GEN-LAST:event_BotaoDeletarMembrosActionPerformed

    private void ReceberCodigoParaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberCodigoParaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberCodigoParaEditarActionPerformed

    private void RecebeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeEmailActionPerformed

    private void RecebeCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeCepActionPerformed

    private void BotaoEditarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarCodigoActionPerformed
        // TODO add your handling code here:
        String codigoCliente = ReceberCodigoParaEditar.getText();
        int codigo = Integer.parseInt(codigoCliente);

        String telefone = RecebeTel.getText();
        String email = RecebeEmail.getText();
        String bairro = RecebeBairro.getText();
        String rua = RecebeRua.getText();
        String numCasa = RecebeNumero.getText();
        String cidade = RecebeCidade.getText();
        String cep = RecebeCep.getText();
        String loginx = RecebeLogin.getText();
        String senha = RecebeSenha.getText();
        
        Classes.Adm.editarMembroTela(codigo, telefone, email, bairro, rua, numCasa, cidade, cep, loginx, senha);
        JOptionPane.showMessageDialog(null, "Membro " + codigo + " Editado com Sucesso!");
        JOptionPane.showMessageDialog(null, "Para Verificar digite o codigo do cliente em Pesquisa e confirme!");
// Limpar os campos de texto
    ReceberCodigoParaEditar.setText("");
    RecebeTel.setText("");
    RecebeEmail.setText("");
    RecebeBairro.setText("");
    RecebeRua.setText("");
    RecebeNumero.setText("");
    RecebeCidade.setText("");
    RecebeCep.setText("");
    RecebeLogin.setText("");
    RecebeSenha.setText("");

    }//GEN-LAST:event_BotaoEditarCodigoActionPerformed

    private void VerTodosOsMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerTodosOsMembrosActionPerformed
        // TODO add your handling code here:
            Classes.Adm.verTodosMembrosTela(mostrarTodosOsMembros);

    }//GEN-LAST:event_VerTodosOsMembrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNconfirmaCadastroMembro;
    private javax.swing.JButton BotaoDeletarMembros;
    private javax.swing.JButton BotaoEditarCodigo;
    private javax.swing.JButton BotaoPesquisarMembros;
    private javax.swing.JTextField RecebeBairro;
    private javax.swing.JTextField RecebeCep;
    private javax.swing.JTextField RecebeCidade;
    private javax.swing.JTextField RecebeEmail;
    private javax.swing.JTextField RecebeLogin;
    private javax.swing.JTextField RecebeNumero;
    private javax.swing.JTextField RecebeRua;
    private javax.swing.JTextField RecebeSenha;
    private javax.swing.JTextField RecebeTel;
    private javax.swing.JTextField ReceberCodigoParaEditar;
    private javax.swing.JTextPane TelaMostrarMembros;
    private javax.swing.JButton VerTodosOsMembros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane mostrarTodosOsMembros;
    private javax.swing.JList<String> opcSelect;
    private javax.swing.JPanel painelCadastroDeFuncionarios;
    private javax.swing.JTextField recebeBairroMembro;
    private javax.swing.JFormattedTextField recebeCepMembro;
    private javax.swing.JTextField recebeCidadeMembro;
    private javax.swing.JTextField recebeCodigoDosMembros;
    private javax.swing.JFormattedTextField recebeCpfMembro;
    private javax.swing.JTextField recebeEmailMembro;
    private javax.swing.JTextField recebeLoginMembro;
    private javax.swing.JTextField recebeNomeMembro;
    private javax.swing.JTextField recebeNumeroMembro;
    private javax.swing.JTextField recebeRuaMembro;
    private javax.swing.JTextField recebeSenhaMembro;
    private javax.swing.JFormattedTextField recebeTelMembro;
    // End of variables declaration//GEN-END:variables
}
