/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TelasDoPrograma;

import Classes.Cliente;
import java.util.List;

/**
 *
 * @author Alan Pablo
 */
public class TelaEditarDadosCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEditarDadosCliente
     */
    public TelaEditarDadosCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        recebeCodigoCliente = new javax.swing.JTextField();
        pesquisarClienteExit = new javax.swing.JButton();
        recebeEmailCliente = new javax.swing.JTextField();
        recebeRuaCliente = new javax.swing.JTextField();
        recebeBairroCliente = new javax.swing.JTextField();
        recebeCidadeCliente = new javax.swing.JTextField();
        recebeNumeroCliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTNeditarDadosDoCliente = new javax.swing.JButton();
        recebeTelCliente = new javax.swing.JFormattedTextField();
        recebeCepCliente = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ver = new javax.swing.JEditorPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Das Do Cliente");

        jLabel11.setText("Codigo Do Cliente");

        pesquisarClienteExit.setText("Pesquisar");
        pesquisarClienteExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClienteExitActionPerformed(evt);
            }
        });

        recebeEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeEmailClienteActionPerformed(evt);
            }
        });

        recebeRuaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeRuaClienteActionPerformed(evt);
            }
        });

        recebeBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recebeBairroClienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Tel:");

        jLabel1.setText("e-mail:");

        jLabel2.setText("Rua:");

        jLabel3.setText("Bairro:");

        jLabel4.setText("Cidade:");

        jLabel5.setText("Numero:");

        jLabel6.setText("Cep:");

        BTNeditarDadosDoCliente.setText("Confirmar Alteração");
        BTNeditarDadosDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeditarDadosDoClienteActionPerformed(evt);
            }
        });

        try {
            recebeTelCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            recebeCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(recebeCidadeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(recebeBairroCliente)
                            .addComponent(recebeRuaCliente)
                            .addComponent(recebeEmailCliente)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recebeTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNeditarDadosDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recebeNumeroCliente)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recebeCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recebeCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pesquisarClienteExit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(recebeCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarClienteExit))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(recebeTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(recebeCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recebeRuaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recebeBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recebeCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(BTNeditarDadosDoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(ver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        setBounds(300, 20, 646, 321);
    }// </editor-fold>//GEN-END:initComponents

    private void recebeEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeEmailClienteActionPerformed

    private void recebeRuaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeRuaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeRuaClienteActionPerformed

    private void recebeBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recebeBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recebeBairroClienteActionPerformed

    private void BTNeditarDadosDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeditarDadosDoClienteActionPerformed
        String tEl = recebeTelCliente.getText();
        String eMail = recebeEmailCliente.getText();
        String rUa = recebeRuaCliente.getText();
        String nUmero = recebeNumeroCliente.getText();
        String bAirro = recebeBairroCliente.getText();
        String cIdade = recebeCidadeCliente.getText();
        String cEp = recebeCepCliente.getText();

        String codigoCliente = recebeCodigoCliente.getText();
        int codigo = Integer.parseInt(codigoCliente);
        
        Cliente edita = new Cliente("David", "david@example.com");
        edita.editarCliente(codigo, tEl, eMail, bAirro, rUa, nUmero, cIdade, cEp);
        
    }//GEN-LAST:event_BTNeditarDadosDoClienteActionPerformed

    private void pesquisarClienteExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClienteExitActionPerformed
        String codigoCliente = recebeCodigoCliente.getText();
        int codigo = Integer.parseInt(codigoCliente);
        List<Cliente> listaClientes = Cliente.verClientes(codigo);

        // Construir a representação em formato de texto
        StringBuilder clienteInfo = new StringBuilder();
        for (Cliente cliente : listaClientes) {
            clienteInfo.append("Código do Cliente: ").append(cliente.getCodigoDoCliente()).append("\n")
                    .append("Telefone: ").append(cliente.getTelefone()).append("\n")
                    .append("E-mail: ").append(cliente.getEmail()).append("\n")
                    .append("Rua: ").append(cliente.getRua()).append("\n")
                    .append("Bairro: ").append(cliente.getBairro()).append("\n")
                    .append("Número da Casa: ").append(cliente.getNumeroCasa()).append("\n")
                    .append("CEP: ").append(cliente.getCep()).append("\n")
                    .append("Cidade: ").append(cliente.getCidade()).append("\n")
                    .append("Nome: ").append(cliente.getNome()).append("\n")
                    .append("CPF: ").append(cliente.getCpf()).append("\n\n");
        }

        ver.setText(clienteInfo.toString());

    }//GEN-LAST:event_pesquisarClienteExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNeditarDadosDoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pesquisarClienteExit;
    private javax.swing.JTextField recebeBairroCliente;
    private javax.swing.JFormattedTextField recebeCepCliente;
    private javax.swing.JTextField recebeCidadeCliente;
    private javax.swing.JTextField recebeCodigoCliente;
    private javax.swing.JTextField recebeEmailCliente;
    private javax.swing.JTextField recebeNumeroCliente;
    private javax.swing.JTextField recebeRuaCliente;
    private javax.swing.JFormattedTextField recebeTelCliente;
    private javax.swing.JEditorPane ver;
    // End of variables declaration//GEN-END:variables
}
