/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelasDoPrograma;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Pablo
 */
public class TelaSistema extends javax.swing.JFrame {

    /**
     * Creates new form TelaSistema
     */
    public TelaSistema() {
        initComponents();
        //abrir em tela cheia
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        popupMenu1 = new java.awt.PopupMenu();
        panel = new javax.swing.JPanel();
        BotaoDeOrdenacaoInicio = new javax.swing.JButton();
        BotaoVerInstanciasClientesProtectPrivate = new javax.swing.JButton();
        BotaoVerInstanciasQuantasClientesReservas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotaoCadastrarClienteInicio = new javax.swing.JButton();
        BotaoPesequisarCliente = new javax.swing.JButton();
        BotaoEditarClienteInicio = new javax.swing.JButton();
        BotaoExcluirClienteInicio = new javax.swing.JButton();
        BotaoVerContaDoCliente = new javax.swing.JButton();
        BotaoFazerReserva = new javax.swing.JButton();
        BotaoPesquisarReservaInicio = new javax.swing.JButton();
        BotaoCancelarReserva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotaoEntrarAdmInicio = new javax.swing.JButton();
        BotatVerReceitaMesInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        infor = new javax.swing.JMenu();
        MenuOrdenacao = new javax.swing.JMenuItem();
        VerInstanciasClientesProtectPrivate = new javax.swing.JMenuItem();
        VerInstanciasQuantasClientesReservas = new javax.swing.JMenuItem();
        clientesOpcoes = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        pesquisaClientes = new javax.swing.JMenuItem();
        EditarCliente = new javax.swing.JMenuItem();
        excluirCliente = new javax.swing.JMenuItem();
        MenuContaCliente = new javax.swing.JMenuItem();
        reservasOpcoes = new javax.swing.JMenu();
        ChamaTelaFazerReserva = new javax.swing.JMenuItem();
        PesquisarReservas = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        opcDoAdm = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        grcFuncionarios = new javax.swing.JRadioButtonMenuItem();
        MenuReceitaMensalDaPousada = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setToolTipText("Sistema da Pousada Milho Verde");

        BotaoDeOrdenacaoInicio.setText("Metodo De Ordenação ");
        BotaoDeOrdenacaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeOrdenacaoInicioActionPerformed(evt);
            }
        });

        BotaoVerInstanciasClientesProtectPrivate.setText("Ver Instancias Clientes");
        BotaoVerInstanciasClientesProtectPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerInstanciasClientesProtectPrivateActionPerformed(evt);
            }
        });

        BotaoVerInstanciasQuantasClientesReservas.setText("Ver Instancias Reservas");
        BotaoVerInstanciasQuantasClientesReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerInstanciasQuantasClientesReservasActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu Da Pousada");

        BotaoCadastrarClienteInicio.setText("Cadastrar Cliente");
        BotaoCadastrarClienteInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarClienteInicioActionPerformed(evt);
            }
        });

        BotaoPesequisarCliente.setText("Pesquisar Cliente");
        BotaoPesequisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesequisarClienteActionPerformed(evt);
            }
        });

        BotaoEditarClienteInicio.setText("Editar Cliente");
        BotaoEditarClienteInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarClienteInicioActionPerformed(evt);
            }
        });

        BotaoExcluirClienteInicio.setText("Excluir Cliente");
        BotaoExcluirClienteInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirClienteInicioActionPerformed(evt);
            }
        });

        BotaoVerContaDoCliente.setText("Ver Conta Cliente");
        BotaoVerContaDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVerContaDoClienteActionPerformed(evt);
            }
        });

        BotaoFazerReserva.setText("Fazer Reserva Cliente");
        BotaoFazerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFazerReservaActionPerformed(evt);
            }
        });

        BotaoPesquisarReservaInicio.setText("Pesquisar Reserva");
        BotaoPesquisarReservaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPesquisarReservaInicioActionPerformed(evt);
            }
        });

        BotaoCancelarReserva.setText("Cancelar Reserva");
        BotaoCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarReservaActionPerformed(evt);
            }
        });

        jLabel2.setText("Menu Administrador");

        BotaoEntrarAdmInicio.setText("Gerencia ADM");
        BotaoEntrarAdmInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEntrarAdmInicioActionPerformed(evt);
            }
        });

        BotatVerReceitaMesInicio.setText("Ver Receita Mensal");
        BotatVerReceitaMesInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotatVerReceitaMesInicioActionPerformed(evt);
            }
        });

        jLabel3.setText("Menu Reservas");

        jLabel4.setText("Menu Cliente");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotaoDeOrdenacaoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoVerInstanciasClientesProtectPrivate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotaoVerInstanciasQuantasClientesReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotatVerReceitaMesInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoEntrarAdmInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCancelarReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoPesquisarReservaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoFazerReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoVerContaDoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoExcluirClienteInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoEditarClienteInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoCadastrarClienteInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotaoPesequisarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(1012, 1012, 1012))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotaoVerInstanciasClientesProtectPrivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVerInstanciasQuantasClientesReservas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoDeOrdenacaoInicio)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCadastrarClienteInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoEditarClienteInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoExcluirClienteInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVerContaDoCliente)
                .addGap(4, 4, 4)
                .addComponent(BotaoPesequisarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoPesquisarReservaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCancelarReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoFazerReserva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoEntrarAdmInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotatVerReceitaMesInicio)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(204, 204, 204)));
        jMenuBar1.setToolTipText("Sistema Da Pousada Milho Verde");
        jMenuBar1.setName("Sistema Da Pousada Milho Verde"); // NOI18N

        infor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/information.png"))); // NOI18N
        infor.setText("Informações");

        MenuOrdenacao.setText("Ordenação ");
        MenuOrdenacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOrdenacaoActionPerformed(evt);
            }
        });
        infor.add(MenuOrdenacao);

        VerInstanciasClientesProtectPrivate.setText("Ver Instancias de Clientes protect e private");
        VerInstanciasClientesProtectPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInstanciasClientesProtectPrivateActionPerformed(evt);
            }
        });
        infor.add(VerInstanciasClientesProtectPrivate);

        VerInstanciasQuantasClientesReservas.setText("Ver Instancias Quantas de Clientes e Reservas");
        VerInstanciasQuantasClientesReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInstanciasQuantasClientesReservasActionPerformed(evt);
            }
        });
        infor.add(VerInstanciasQuantasClientesReservas);

        jMenuBar1.add(infor);

        clientesOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        clientesOpcoes.setText("Clientes");

        cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_add.png"))); // NOI18N
        cadCliente.setText("Cadastrar Cliente");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });
        clientesOpcoes.add(cadCliente);

        pesquisaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom.png"))); // NOI18N
        pesquisaClientes.setText("Pesquisar Cliente");
        pesquisaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaClientesActionPerformed(evt);
            }
        });
        clientesOpcoes.add(pesquisaClientes);

        EditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_edit.png"))); // NOI18N
        EditarCliente.setText("Editar Cadastro Cliente");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });
        clientesOpcoes.add(EditarCliente);

        excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        excluirCliente.setText("Excluir Cliente");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });
        clientesOpcoes.add(excluirCliente);

        MenuContaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_add.png"))); // NOI18N
        MenuContaCliente.setText("Ver Conta do Cliente");
        MenuContaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContaClienteActionPerformed(evt);
            }
        });
        clientesOpcoes.add(MenuContaCliente);

        jMenuBar1.add(clientesOpcoes);

        reservasOpcoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house.png"))); // NOI18N
        reservasOpcoes.setText("Reservas");

        ChamaTelaFazerReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house_go.png"))); // NOI18N
        ChamaTelaFazerReserva.setText("Cadastrar Reserva");
        ChamaTelaFazerReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChamaTelaFazerReservaActionPerformed(evt);
            }
        });
        reservasOpcoes.add(ChamaTelaFazerReserva);

        PesquisarReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/zoom.png"))); // NOI18N
        PesquisarReservas.setText("Pesquisar Reserva");
        PesquisarReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarReservasActionPerformed(evt);
            }
        });
        reservasOpcoes.add(PesquisarReservas);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jMenuItem7.setText("Cancelar Reserva");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        reservasOpcoes.add(jMenuItem7);

        jMenuBar1.add(reservasOpcoes);

        opcDoAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_gray.png"))); // NOI18N
        opcDoAdm.setText("Configurações");
        opcDoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcDoAdmActionPerformed(evt);
            }
        });

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money_dollar.png"))); // NOI18N
        jMenu6.setText("Opções De Administrador");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        grcFuncionarios.setSelected(true);
        grcFuncionarios.setText("Gerenciar Funcionarios");
        grcFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grcFuncionariosActionPerformed(evt);
            }
        });
        jMenu6.add(grcFuncionarios);

        MenuReceitaMensalDaPousada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        MenuReceitaMensalDaPousada.setText("Extrato Mensal da Pousada");
        MenuReceitaMensalDaPousada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReceitaMensalDaPousadaActionPerformed(evt);
            }
        });
        jMenu6.add(MenuReceitaMensalDaPousada);

        opcDoAdm.add(jMenu6);

        jMenuBar1.add(opcDoAdm);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("Sistema Da Pousada Milho Verde");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel.getAccessibleContext().setAccessibleName("Sistema da Pousada Milho Verde");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
        TelaEditarDadosCliente editaCliente = new TelaEditarDadosCliente();
        panel.add(editaCliente);
        editaCliente.setVisible(true);
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        TeladeCadastrosCliente cadasCliente = new TeladeCadastrosCliente();
        panel.add(cadasCliente);
        cadasCliente.setVisible(true);


    }//GEN-LAST:event_cadClienteActionPerformed

    private void pesquisaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaClientesActionPerformed
        TelaPesquisarClientes pesqCliente = new TelaPesquisarClientes();
        panel.add(pesqCliente);
        pesqCliente.setVisible(true);    }//GEN-LAST:event_pesquisaClientesActionPerformed

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteActionPerformed
        TelaExcluirCliente delCliente = new TelaExcluirCliente();
        panel.add(delCliente);
        delCliente.setVisible(true);
    }//GEN-LAST:event_excluirClienteActionPerformed

    private void opcDoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcDoAdmActionPerformed
        //adm

    }//GEN-LAST:event_opcDoAdmActionPerformed

    private void grcFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grcFuncionariosActionPerformed
        TelaOpcoesAdm opcAdm = new TelaOpcoesAdm();
        panel.add(opcAdm);
        opcAdm.setVisible(true);    }//GEN-LAST:event_grcFuncionariosActionPerformed

    private void ChamaTelaFazerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChamaTelaFazerReservaActionPerformed
        // TODO add your handling code here:
        TelaFazerReserva cadasReserva = new TelaFazerReserva();
        panel.add(cadasReserva);
        cadasReserva.setVisible(true);
    }//GEN-LAST:event_ChamaTelaFazerReservaActionPerformed

    private void PesquisarReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarReservasActionPerformed
        // TODO add your handling code here:
        TelaPesquisarReserva pesReserva = new TelaPesquisarReserva();
        panel.add(pesReserva);
        pesReserva.setVisible(true);
    }//GEN-LAST:event_PesquisarReservasActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        TelaCancelarReserva cancelRes = new TelaCancelarReserva();
        panel.add(cancelRes);
        cancelRes.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void MenuOrdenacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOrdenacaoActionPerformed
        // TODO add your handling code here:
        TelaMetodosDeOrdenação ordena = new TelaMetodosDeOrdenação();
        panel.add(ordena);
        ordena.setVisible(true);
    }//GEN-LAST:event_MenuOrdenacaoActionPerformed

    private void MenuContaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContaClienteActionPerformed
        // TODO add your handling code here:
        TelaContaDoCliente ordena = new TelaContaDoCliente();
        panel.add(ordena);
        ordena.setVisible(true);
    }//GEN-LAST:event_MenuContaClienteActionPerformed

    private void MenuReceitaMensalDaPousadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReceitaMensalDaPousadaActionPerformed
        // TODO add your handling code here:
        TelaReceitaMensalPousada receita = new TelaReceitaMensalPousada();
        panel.add(receita);
        receita.setVisible(true);
    }//GEN-LAST:event_MenuReceitaMensalDaPousadaActionPerformed

    private void VerInstanciasClientesProtectPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInstanciasClientesProtectPrivateActionPerformed
        // TODO add your handling code here:

        String mensagem = "";

        try (FileReader reader = new FileReader("./src/arquivos/CLIENTESX.json")) {
            JsonParser jsonParser = new JsonParser();
            JsonObject jsonObject = jsonParser.parse(reader).getAsJsonObject();

            int contadorEncapsulamento = jsonObject.get("contadorEncapsulamento").getAsInt();
            int contadorProtegido = jsonObject.get("contadorProtegido").getAsInt();

            mensagem += "Instâncias de Cliente Encapsulamento: " + contadorEncapsulamento + "\n";
            mensagem += "Instâncias de Cliente Protegido: " + contadorProtegido + "\n";
        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, mensagem);

    }//GEN-LAST:event_VerInstanciasClientesProtectPrivateActionPerformed

    private void VerInstanciasQuantasClientesReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInstanciasQuantasClientesReservasActionPerformed
        // TODO add your handling code here:
        String mensagem = "";

        int instanciaReserva = arquivos.JsonFerramentas.lerInstanciaReserva();
        mensagem += "Número de instâncias de Reserva: " + instanciaReserva + "\n";

        try (FileReader reader = new FileReader("./src/arquivos/CLIENTESX.json")) {
            JsonParser jsonParser = new JsonParser();
            JsonObject jsonObject = jsonParser.parse(reader).getAsJsonObject();

            int contadorEncapsulamento = jsonObject.get("contadorEncapsulamento").getAsInt();
            int contadorProtegido = jsonObject.get("contadorProtegido").getAsInt();

            mensagem += "Instâncias de Cliente Encapsulamento: " + contadorEncapsulamento + "\n";
            mensagem += "Instâncias de Cliente Protegido: " + contadorProtegido + "\n";
        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, mensagem);


    }//GEN-LAST:event_VerInstanciasQuantasClientesReservasActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed


    }//GEN-LAST:event_jMenu6ActionPerformed

    private void BotaoDeOrdenacaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeOrdenacaoInicioActionPerformed
        TelaMetodosDeOrdenação ordena = new TelaMetodosDeOrdenação();
        panel.add(ordena);
        ordena.setVisible(true);


    }//GEN-LAST:event_BotaoDeOrdenacaoInicioActionPerformed

    private void BotaoVerInstanciasClientesProtectPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerInstanciasClientesProtectPrivateActionPerformed

        String mensagem = "";

        try (FileReader reader = new FileReader("./src/arquivos/CLIENTESX.json")) {
            JsonParser jsonParser = new JsonParser();
            JsonObject jsonObject = jsonParser.parse(reader).getAsJsonObject();

            int contadorEncapsulamento = jsonObject.get("contadorEncapsulamento").getAsInt();
            int contadorProtegido = jsonObject.get("contadorProtegido").getAsInt();

            mensagem += "Instâncias de Cliente Encapsulamento: " + contadorEncapsulamento + "\n";
            mensagem += "Instâncias de Cliente Protegido: " + contadorProtegido + "\n";
        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, mensagem);

    }//GEN-LAST:event_BotaoVerInstanciasClientesProtectPrivateActionPerformed

    private void BotaoVerInstanciasQuantasClientesReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerInstanciasQuantasClientesReservasActionPerformed
        String mensagem = "";

        int instanciaReserva = arquivos.JsonFerramentas.lerInstanciaReserva();
        mensagem += "Número de instâncias de Reserva: " + instanciaReserva + "\n";

        try (FileReader reader = new FileReader("./src/arquivos/CLIENTESX.json")) {
            JsonParser jsonParser = new JsonParser();
            JsonObject jsonObject = jsonParser.parse(reader).getAsJsonObject();

            int contadorEncapsulamento = jsonObject.get("contadorEncapsulamento").getAsInt();
            int contadorProtegido = jsonObject.get("contadorProtegido").getAsInt();

            mensagem += "Instâncias de Cliente Encapsulamento: " + contadorEncapsulamento + "\n";
            mensagem += "Instâncias de Cliente Protegido: " + contadorProtegido + "\n";
        } catch (IOException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(null, mensagem);


    }//GEN-LAST:event_BotaoVerInstanciasQuantasClientesReservasActionPerformed

    private void BotaoCadastrarClienteInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarClienteInicioActionPerformed
        TeladeCadastrosCliente cadasCliente = new TeladeCadastrosCliente();
        panel.add(cadasCliente);
        cadasCliente.setVisible(true);

    }//GEN-LAST:event_BotaoCadastrarClienteInicioActionPerformed

    private void BotaoPesequisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesequisarClienteActionPerformed
        TelaPesquisarClientes pesqCliente = new TelaPesquisarClientes();
        panel.add(pesqCliente);
        pesqCliente.setVisible(true);

    }//GEN-LAST:event_BotaoPesequisarClienteActionPerformed

    private void BotaoEditarClienteInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEditarClienteInicioActionPerformed
        TelaEditarDadosCliente editaCliente = new TelaEditarDadosCliente();
        panel.add(editaCliente);
        editaCliente.setVisible(true);

    }//GEN-LAST:event_BotaoEditarClienteInicioActionPerformed

    private void BotaoExcluirClienteInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirClienteInicioActionPerformed
        TelaExcluirCliente delCliente = new TelaExcluirCliente();
        panel.add(delCliente);
        delCliente.setVisible(true);

    }//GEN-LAST:event_BotaoExcluirClienteInicioActionPerformed

    private void BotaoVerContaDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVerContaDoClienteActionPerformed
        TelaContaDoCliente ordena = new TelaContaDoCliente();
        panel.add(ordena);
        ordena.setVisible(true);

    }//GEN-LAST:event_BotaoVerContaDoClienteActionPerformed

    private void BotaoFazerReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFazerReservaActionPerformed
        TelaFazerReserva cadasReserva = new TelaFazerReserva();
        panel.add(cadasReserva);
        cadasReserva.setVisible(true);

    }//GEN-LAST:event_BotaoFazerReservaActionPerformed

    private void BotaoPesquisarReservaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPesquisarReservaInicioActionPerformed
        TelaPesquisarReserva pesReserva = new TelaPesquisarReserva();
        panel.add(pesReserva);
        pesReserva.setVisible(true);

    }//GEN-LAST:event_BotaoPesquisarReservaInicioActionPerformed

    private void BotaoCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarReservaActionPerformed
        TelaCancelarReserva cancelRes = new TelaCancelarReserva();
        panel.add(cancelRes);
        cancelRes.setVisible(true);

    }//GEN-LAST:event_BotaoCancelarReservaActionPerformed

    private void BotaoEntrarAdmInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEntrarAdmInicioActionPerformed
        TelaOpcoesAdm opcAdm = new TelaOpcoesAdm();
        panel.add(opcAdm);
        opcAdm.setVisible(true);

    }//GEN-LAST:event_BotaoEntrarAdmInicioActionPerformed

    private void BotatVerReceitaMesInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotatVerReceitaMesInicioActionPerformed
        TelaReceitaMensalPousada receita = new TelaReceitaMensalPousada();
        panel.add(receita);
        receita.setVisible(true);

    }//GEN-LAST:event_BotatVerReceitaMesInicioActionPerformed

    
    public static void Sistema() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarClienteInicio;
    private javax.swing.JButton BotaoCancelarReserva;
    private javax.swing.JButton BotaoDeOrdenacaoInicio;
    private javax.swing.JButton BotaoEditarClienteInicio;
    private javax.swing.JButton BotaoEntrarAdmInicio;
    private javax.swing.JButton BotaoExcluirClienteInicio;
    private javax.swing.JButton BotaoFazerReserva;
    private javax.swing.JButton BotaoPesequisarCliente;
    private javax.swing.JButton BotaoPesquisarReservaInicio;
    private javax.swing.JButton BotaoVerContaDoCliente;
    private javax.swing.JButton BotaoVerInstanciasClientesProtectPrivate;
    private javax.swing.JButton BotaoVerInstanciasQuantasClientesReservas;
    private javax.swing.JButton BotatVerReceitaMesInicio;
    private javax.swing.JMenuItem ChamaTelaFazerReserva;
    private javax.swing.JMenuItem EditarCliente;
    private javax.swing.JMenuItem MenuContaCliente;
    private javax.swing.JMenuItem MenuOrdenacao;
    private javax.swing.JMenuItem MenuReceitaMensalDaPousada;
    private javax.swing.JMenuItem PesquisarReservas;
    private javax.swing.JMenuItem VerInstanciasClientesProtectPrivate;
    private javax.swing.JMenuItem VerInstanciasQuantasClientesReservas;
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenu clientesOpcoes;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JRadioButtonMenuItem grcFuncionarios;
    private javax.swing.JMenu infor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JMenu opcDoAdm;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem pesquisaClientes;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JMenu reservasOpcoes;
    // End of variables declaration//GEN-END:variables
}
