/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TelasDoPrograma;

import Classes.Cliente;
import java.util.List;

/**
 *
 * @author Alan Pablo
 */
public class TelaExcluirCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaExcluirCliente
     */
    public TelaExcluirCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recebeCodigoCliente = new javax.swing.JTextField();
        pesquisarClienteExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ver = new javax.swing.JTextPane();
        BTNexcluirCliente = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Excluir Cliente");

        pesquisarClienteExit.setText("Pesquisar");
        pesquisarClienteExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarClienteExitActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar Cliente");

        jScrollPane1.setViewportView(ver);

        BTNexcluirCliente.setText("Deletar Cliente");
        BTNexcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexcluirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(recebeCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pesquisarClienteExit))
            .addComponent(jLabel1)
            .addComponent(jScrollPane1)
            .addComponent(BTNexcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recebeCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisarClienteExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNexcluirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(300, 20, 236, 343);
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarClienteExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarClienteExitActionPerformed
        String codigoCliente = recebeCodigoCliente.getText();
        int codigo = Integer.parseInt(codigoCliente);
        List<Cliente> listaClientes = Cliente.verClientes(codigo);

        // Construir a representação em formato de texto
        StringBuilder clienteInfo = new StringBuilder();
        for (Cliente cliente : listaClientes) {
            clienteInfo.append("Código do Cliente: ").append(cliente.getCodigoDoCliente()).append("\n")
                    .append("Telefone: ").append(cliente.getTelefone()).append("\n")
                    .append("E-mail: ").append(cliente.getEmail()).append("\n")
                    .append("Rua: ").append(cliente.getRua()).append("\n")
                    .append("Bairro: ").append(cliente.getBairro()).append("\n")
                    .append("Número da Casa: ").append(cliente.getNumeroCasa()).append("\n")
                    .append("CEP: ").append(cliente.getCep()).append("\n")
                    .append("Cidade: ").append(cliente.getCidade()).append("\n")
                    .append("Nome: ").append(cliente.getNome()).append("\n")
                    .append("CPF: ").append(cliente.getCpf()).append("\n\n");
        }

        ver.setText(clienteInfo.toString());

            
    }//GEN-LAST:event_pesquisarClienteExitActionPerformed

    private void BTNexcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexcluirClienteActionPerformed
        String codigoCliente = recebeCodigoCliente.getText();
        int codigo = Integer.parseInt(codigoCliente);
        List<Cliente> listaClientes = Cliente.verClientes(codigo);
        
        Cliente deletCliente = new Cliente("David", "david@example.com");
        deletCliente.excluirCliente(codigo);
    }//GEN-LAST:event_BTNexcluirClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNexcluirCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pesquisarClienteExit;
    private javax.swing.JTextField recebeCodigoCliente;
    private javax.swing.JTextPane ver;
    // End of variables declaration//GEN-END:variables
}
